const navData = [
  {
    id: 1,
    name: '首页',
    title: '首页',
    meta: {title: '首页'},
    path: '/home',
    icons: 'House',
    component: 'home/index',
    children:[],
  },
  {
    id: 2,
    name: '系统管理',
    title: '系统管理',
    meta: {title: '系统管理'},
    path: '/system',
    icons: 'Setting',
    component: 'system/index',
    children: [
      {
        id: 3,
        name: '用户管理',
        title: '用户管理',
        meta: {title: '用户管理'},
        path: '/system/user',
        icons: 'User',
        component: 'system/user',
        children:[],
      },
      {
        id: 4,
        name: '菜单管理',
        title: '菜单管理',
        meta: {title: '菜单管理'},
        path: '/system/menu',
        icons: 'Menu',
        component: 'system/menu',
        children:[],
      },
      {
        id: 5,
        name: '角色管理',
        title: '角色管理',
        meta: {title: '角色管理'},
        path: '/system/role',
        icons: 'Avatar',
        component: 'system/role',
        children:[],
      },
      {
        id: 7,
        name: '文件管理',
        title: '文件管理',
        meta: {title: '文件管理'},
        path: '/system/files',
        icons: 'Avatar',
        component: 'system/files',
        children:[],
      },
      {
        id: 8,
        name: '机构管理',
        title: '机构管理',
        meta: {title: '机构管理'},
        path: '/system/org',
        icons: 'Avatar',
        component: 'system/org',
        children:[],
      },
    ],
  },
  {
    id: 6,
    name: '产品管理',
    title: '产品管理',
    meta: {title: '产品管理'},
    path: '/product',
    icons: 'Shop',
    component: 'product/index',
    children:[],
  },
];

export default navData;
